In [1]:
#Importando a Biblioteca
import numpy as np

In [6]:
quantidade_produtos = [10, 5, 3, 8] #Lista
print(type(quantidade_produtos))
custo_produtos = [5, 10, 2, 3] #Lista
array_quantidade = np.array(quantidade_produtos) #Array
array_custo = np.array(custo_produtos) #Array
faturamento = array_quantidade * array_custo
print(faturamento)
print(type(faturamento))

<class 'list'>
[50 50  6 24]
<class 'numpy.ndarray'>


In [10]:
#Gerar um Array automático
np.arange(10,21)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [11]:
#Gerar um array com passo
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [ ]:
#Zerando as listas:
custo_produtos = []
venda_produtos = []
#Pegando o preço de custo de todos os produtos:
custo1 = int(input("Digite o valor de Custo do Produto 1: "))
custo2 = int(input("Digite o valor de Custo do Produto 2: "))
custo3 = int(input("Digite o valor de Custo do Produto 3: "))
custo4 = int(input("Digite o valor de Custo do Produto 4: "))
custo5 = int(input("Digite o valor de Custo do Produto 5: "))
#Pegando o preço de venda de todos os produtos:
venda1 = int(input("Digite o valor de Venda do Produto 1: "))
venda2 = int(input("Digite o valor de Venda do Produto 2: "))
venda3 = int(input("Digite o valor de Venda do Produto 3: "))
venda4 = int(input("Digite o valor de Venda do Produto 4: "))
venda5 = int(input("Digite o valor de Venda do Produto 5: "))
#Criando Array com os valores de custo digitados acima:
custo_produtos.append(custo1)
custo_produtos.append(custo2)
custo_produtos.append(custo3)
custo_produtos.append(custo4)
custo_produtos.append(custo5)
#Criando Array com os valores de venda digitados acima:
venda_produtos.append(venda1)
venda_produtos.append(venda2)
venda_produtos.append(venda3)
venda_produtos.append(venda4)
venda_produtos.append(venda5)
array_custo = np.array(custo_produtos)
array_venda = np.array(venda_produtos)
lucro = array_venda - array_custo
print(lucro)

[2 2 2 2 2]


In [15]:
salarios = np.array([2,3,4,5,6,500])
maior_salario = np.max(salarios)
print(maior_salario)

500


In [19]:
menor_salario = np.min(salarios)
print(menor_salario)

2


In [16]:
media_salarios = np.mean(salarios)
print(f"{media_salarios:.2f}")

86.67


In [18]:
mediana_salarios = np.median(salarios)
print(mediana_salarios)

4.5


In [20]:
#Desvio Padrão
desvio = np.std(salarios)
print(desvio)

184.852794286577


In [25]:
#Criação de Array Vendas
vendas = np.array([10,20,45,5,90])
#Pegando a maior venda da Array Vendas
maior_venda = np.max(vendas)
#Pegando a menor venda da Array Vendas
menor_venda = np.min(vendas)
#Pegando a média de venda da Array Vendas
media_venda = np.mean(vendas)
#Pegando a mediana de venda da Array Vendas
mediana_venda = np.median(vendas)
#Exibindo a maior venda
print(f"A maior venda foi: {maior_venda}")
#Exibindo a menor venda
print(f"A menor venda foi: {menor_venda}")
#Exibindo a média das vendas
print(f"A média de Venda foi: {media_venda}")
#Exibindo a mediana de vendas
print(f"A mediana de Venda foi: {mediana_venda}")

A maior venda foi: 90
A menor venda foi: 5
A média de Venda foi: 34.0
A mediana de Venda foi: 20.0
